@php
$items=old('items',$section->items?->map(fn($item)=>['title'=>$item->title,'subtitle'=>$item->subtitle,'body'=>$item->body,'existing_image'=>$item->image,'link_label'=>$item->link_label,'link_url'=>$item->link_url,'meta_role'=>$item->meta['role']??null])->values()->all()??[]);
if(!$items)$items=[[]];
@endphp
<style>
.hf{max-width:1260px;margin:auto;color:#23324a}.hf-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.hf-head h1{font-size:28px;margin:4px 0}.hf-layout{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:18px}.hf-card{margin-bottom:18px;border:1px solid #e0e7f0;border-radius:13px;background:#fff;overflow:hidden}.hf-card-head{padding:18px 20px;border-bottom:1px solid #e8edf3}.hf-card-head h2{font-size:17px;margin:0 0 4px}.hf-card-head p{font-size:12px;color:#7c899c;margin:0}.hf-body{padding:20px}.hf-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.hf-field.full{grid-column:1/-1}.hf-field label{display:block;margin-bottom:6px;font-size:12px;font-weight:800}.hf-field input,.hf-field select,.hf-field textarea{width:100%;padding:11px 12px;border:1px solid #d8e1ec;border-radius:8px;font:inherit}.hf-field textarea{min-height:100px}.hf-help{display:block;color:#8995a7;font-size:10px;margin-top:5px}.hf-items{display:grid;gap:12px}.hf-item{position:relative;padding:17px;border:1px solid #e1e8f1;border-radius:11px;background:#fafbfd}.hf-item-title{font-size:11px;font-weight:800;color:#8490a2;text-transform:uppercase;margin-bottom:12px}.hf-remove{position:absolute;right:12px;top:10px;border:0;background:#fff0f1;color:#c53b46;border-radius:7px;width:32px;height:32px}.hf-thumb{width:90px;height:62px;object-fit:cover;border-radius:7px;margin:7px 0}.hf-btn{display:inline-flex;align-items:center;justify-content:center;gap:6px;padding:11px 15px;border:1px solid #d9e2ed;border-radius:8px;background:#fff;color:#40516b;text-decoration:none;font-weight:700}.hf-btn.primary{background:#397ef6;border-color:#397ef6;color:#fff}.hf-side{position:sticky;top:80px}.hf-switch{display:flex;justify-content:space-between;align-items:center;padding:15px;border-radius:9px;background:#f5f8fc}.hf-errors{padding:14px 18px;border-radius:9px;background:#fff0f1;color:#a92e39;margin-bottom:16px}.type-note{padding:12px;border-radius:8px;background:#eef5ff;color:#48617f;font-size:12px;line-height:1.5}@media(max-width:850px){.hf-layout{grid-template-columns:1fr}.hf-side{position:static}.hf-grid{grid-template-columns:1fr}.hf-field.full{grid-column:auto}.hf-head{align-items:flex-start;flex-direction:column;gap:12px}}
</style>
<div class="hf"><div class="hf-head"><div><div class="text-primary">Homepage / {{$section->exists?'Edit':'Add section'}}</div><h1>{{$section->exists?'Edit '.$section->name:'Create a homepage section'}}</h1></div><a class="hf-btn" href="{{route('admin.homepage.index')}}">Back to sections</a></div>
@if($errors->any())<div class="hf-errors"><b>Please correct the highlighted information.</b><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<form method="post" enctype="multipart/form-data" action="{{$section->exists?route('admin.homepage.update',$section):route('admin.homepage.store')}}">@csrf @if($section->exists)@method('PUT')@endif
<div class="hf-layout"><main><section class="hf-card"><div class="hf-card-head"><h2>Section setup</h2><p>Choose what this block does and add its public heading.</p></div><div class="hf-body"><div class="hf-grid">
<div class="hf-field"><label>Section type *</label><select name="type" id="sectionType">@foreach($types as $value=>$label)<option value="{{$value}}" @selected(old('type',$section->type)===$value)>{{$label}}</option>@endforeach</select></div>
<div class="hf-field"><label>Admin name *</label><input name="name" value="{{old('name',$section->name)}}" required placeholder="Example: Customer success stories"><span class="hf-help">Only administrators see this name.</span></div>
<div class="hf-field"><label>Small heading</label><input name="eyebrow" value="{{old('eyebrow',$section->eyebrow)}}" placeholder="Example: How it works"></div>
<div class="hf-field"><label>Main heading</label><input name="title" value="{{old('title',$section->title)}}"></div>
<div class="hf-field full"><label>Introduction</label><textarea name="body">{{old('body',$section->body)}}</textarea></div>
</div></div></section>
<section class="hf-card item-card"><div class="hf-card-head"><h2 id="itemsHeading">Content items</h2><p id="itemsHelp">Add and order the content shown inside this section.</p></div><div class="hf-body"><div class="type-note mb-3" id="typeNote"></div><div class="hf-items" id="items">@foreach($items as $i=>$item)<div class="hf-item" data-index="{{$i}}"><button type="button" class="hf-remove" aria-label="Remove item">×</button><div class="hf-item-title">Item {{$i+1}}</div><div class="hf-grid">
<div class="hf-field item-title"><label>Title</label><input name="items[{{$i}}][title]" value="{{$item['title']??''}}"></div><div class="hf-field item-subtitle"><label>Subtitle</label><input name="items[{{$i}}][subtitle]" value="{{$item['subtitle']??''}}"></div>
<div class="hf-field full item-body"><label>Description</label><textarea name="items[{{$i}}][body]">{{$item['body']??''}}</textarea></div>
<div class="hf-field item-image"><label>Image</label>@if($item['existing_image']??null)<img class="hf-thumb" src="{{url('public/'.$item['existing_image'])}}" alt=""><input type="hidden" name="items[{{$i}}][existing_image]" value="{{$item['existing_image']}}">@endif<input type="file" name="items[{{$i}}][image]" accept="image/jpeg,image/png,image/webp"><span class="hf-help">JPG, PNG or WebP; maximum 5 MB.</span></div>
<div class="hf-field item-role"><label>Person role / company</label><input name="items[{{$i}}][meta_role]" value="{{$item['meta_role']??''}}"></div>
<div class="hf-field item-link-label"><label>Button label</label><input name="items[{{$i}}][link_label]" value="{{$item['link_label']??''}}"></div><div class="hf-field item-link-url"><label>Button link</label><input name="items[{{$i}}][link_url]" value="{{$item['link_url']??''}}" placeholder="/join or https://..."></div>
</div></div>@endforeach</div><button type="button" class="hf-btn mt-3" id="addItem"><i class="fa fa-plus"></i> Add another item</button></div></section></main>
<aside><div class="hf-side"><section class="hf-card"><div class="hf-card-head"><h2>Publishing</h2><p>Control visibility and position.</p></div><div class="hf-body"><div class="hf-switch"><div><b>Show publicly</b><div class="hf-help">You can hide it without deleting content.</div></div><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$section->is_active))></div><div class="hf-field mt-3"><label>Display order</label><input type="number" name="sort_order" value="{{old('sort_order',$section->sort_order)}}" min="0"><span class="hf-help">Lower numbers appear first.</span></div><button class="hf-btn primary mt-3" style="width:100%">Save section</button></div></section>
<section class="hf-card settings-card"><div class="hf-card-head"><h2>Buttons and options</h2></div><div class="hf-body"><div class="hf-field"><label>Primary button label</label><input name="settings[button_label]" value="{{old('settings.button_label',$section->settings['button_label']??'')}}"></div><div class="hf-field mt-3"><label>Primary link</label><input name="settings[button_url]" value="{{old('settings.button_url',$section->settings['button_url']??'')}}"></div><div class="hf-field mt-3"><label>Secondary button label</label><input name="settings[secondary_label]" value="{{old('settings.secondary_label',$section->settings['secondary_label']??'')}}"></div><div class="hf-field mt-3"><label>Secondary link</label><input name="settings[secondary_url]" value="{{old('settings.secondary_url',$section->settings['secondary_url']??'')}}"></div><div class="hf-field mt-3 event-limit"><label>Number of events</label><input type="number" min="1" max="12" name="settings[limit]" value="{{old('settings.limit',$section->settings['limit']??3)}}"></div></div></section></div></aside></div></form></div>
<template id="itemTemplate"><div class="hf-item"><button type="button" class="hf-remove" aria-label="Remove item">×</button><div class="hf-item-title">New item</div><div class="hf-grid"><div class="hf-field item-title"><label>Title</label><input data-name="title"></div><div class="hf-field item-subtitle"><label>Subtitle</label><input data-name="subtitle"></div><div class="hf-field full item-body"><label>Description</label><textarea data-name="body"></textarea></div><div class="hf-field item-image"><label>Image</label><input type="file" data-name="image" accept="image/jpeg,image/png,image/webp"></div><div class="hf-field item-role"><label>Person role / company</label><input data-name="meta_role"></div><div class="hf-field item-link-label"><label>Button label</label><input data-name="link_label"></div><div class="hf-field item-link-url"><label>Button link</label><input data-name="link_url"></div></div></div></template>
<script>
(()=>{const type=document.getElementById('sectionType'),items=document.getElementById('items'),template=document.getElementById('itemTemplate');const config={hero:{note:'Each item is one carousel slide. Add a large image, headline, supporting text and optional button.',heading:'Carousel slides',show:['title','subtitle','body','image','link-label','link-url']},steps:{note:'Each item is one numbered step. Keep titles and descriptions short.',heading:'Process steps',show:['title','body']},features:{note:'Use cards to explain benefits, services or important features.',heading:'Feature cards',show:['title','body','image','link-label','link-url']},content:{note:'Use one or more blocks for detailed content with optional supporting images.',heading:'Content blocks',show:['title','body','image','link-label','link-url']},gallery:{note:'Upload images with clear titles or short captions.',heading:'Gallery images',show:['title','subtitle','image']},testimonials:{note:'Title is the person’s name, description is their testimonial, and role identifies their company or designation.',heading:'Testimonials',show:['title','body','image','role']},events:{note:'Upcoming published events are loaded automatically. No manual items are needed.',heading:'Automatic event feed',show:[]},cta:{note:'Use the section heading, description and button options. No manual items are needed.',heading:'Call to action',show:[]}};function renumber(){[...items.children].forEach((row,i)=>{row.dataset.index=i;row.querySelector('.hf-item-title').textContent='Item '+(i+1);row.querySelectorAll('[name]').forEach(field=>field.name=field.name.replace(/items\[\d+\]/,`items[${i}]`));row.querySelectorAll('[data-name]').forEach(field=>field.name=`items[${i}][${field.dataset.name}]`)})}function apply(){const c=config[type.value];document.getElementById('itemsHeading').textContent=c.heading;document.getElementById('typeNote').textContent=c.note;document.querySelector('.item-card').style.display=c.show.length?'block':'none';document.querySelector('.event-limit').style.display=type.value==='events'?'block':'none';document.querySelectorAll('.hf-item').forEach(row=>['title','subtitle','body','image','role','link-label','link-url'].forEach(name=>{const el=row.querySelector('.item-'+name);if(el)el.style.display=c.show.includes(name)?'block':'none'}))}document.getElementById('addItem').onclick=()=>{items.append(template.content.cloneNode(true));renumber();bind();apply()};function bind(){document.querySelectorAll('.hf-remove').forEach(button=>button.onclick=()=>{if(items.children.length>1)button.closest('.hf-item').remove();else button.closest('.hf-item').querySelectorAll('input,textarea').forEach(field=>field.value='');renumber()})}type.onchange=apply;bind();renumber();apply()})();
</script>
