<style>
.hp{max-width:1320px;margin:auto;color:#23324a}.hp-head{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:22px}.hp-head h1{font-size:29px;margin:4px 0}.hp-head p{margin:0;color:#748198}.hp-actions{display:flex;gap:9px}.hp-btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;padding:11px 15px;border:1px solid #dbe3ed;border-radius:9px;background:#fff;color:#40516b;text-decoration:none;font-weight:700}.hp-btn.primary{background:#397ef6;border-color:#397ef6;color:#fff}.hp-card{overflow:hidden;border:1px solid #e0e7f0;border-radius:14px;background:#fff;box-shadow:0 8px 28px #1b2b4510}.hp-intro{display:flex;align-items:center;justify-content:space-between;padding:20px 22px;border-bottom:1px solid #e7ecf3}.hp-intro h2{font-size:18px;margin:0 0 4px}.hp-intro span{font-size:13px;color:#7c899e}.hp-row{display:grid;grid-template-columns:54px minmax(260px,1fr) 160px 100px 205px;gap:16px;align-items:center;padding:15px 20px;border-bottom:1px solid #edf1f5}.hp-row:last-child{border-bottom:0}.hp-order{display:flex;gap:5px}.hp-order form{margin:0}.hp-icon{width:39px;height:39px;border:1px solid #dfe6ef;border-radius:8px;background:#f7f9fc;color:#65758d}.hp-name strong{display:block}.hp-name span{font-size:12px;color:#8290a4}.hp-type{font-size:12px;font-weight:700;color:#52637c}.hp-pill{display:inline-block;padding:6px 9px;border-radius:20px;background:#e9f7f0;color:#198457;font-size:10px;font-weight:800;text-transform:uppercase}.hp-pill.off{background:#f0f2f5;color:#788599}.hp-row-actions{display:flex;justify-content:flex-end;gap:7px}.hp-row-actions form{margin:0}.hp-empty{padding:55px;text-align:center;color:#788599}@media(max-width:850px){.hp-head,.hp-intro{align-items:flex-start;flex-direction:column}.hp-row{grid-template-columns:44px 1fr}.hp-type,.hp-status{display:none}.hp-row-actions{grid-column:2;justify-content:flex-start}}
</style>
<div class="hp">
 <div class="hp-head"><div><div class="text-primary">Website / Homepage</div><h1>Homepage CMS</h1><p>Build your homepage using flexible, ordered content sections.</p></div><div class="hp-actions"><a class="hp-btn" href="{{url('/')}}" target="_blank"><i class="fa fa-eye"></i> Preview</a><a class="hp-btn primary" href="{{route('admin.homepage.create')}}"><i class="fa fa-plus"></i> Add section</a></div></div>
 @if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
 <div class="hp-card"><div class="hp-intro"><div><h2>Page sections</h2><span>Use the arrows to control the order. Hidden sections remain saved but are not visible publicly.</span></div><b>{{$sections->count()}} sections</b></div>
 @forelse($sections as $section)<div class="hp-row">
  <div class="hp-order"><form method="post" action="{{route('admin.homepage.move',[$section,'up'])}}">@csrf<button class="hp-icon" title="Move up">↑</button></form><form method="post" action="{{route('admin.homepage.move',[$section,'down'])}}">@csrf<button class="hp-icon" title="Move down">↓</button></form></div>
  <div class="hp-name"><strong>{{$section->name}}</strong><span>{{$section->title ?: 'No public heading'}} · {{$section->items_count}} items</span></div>
  <div class="hp-type">{{ucwords(str_replace('_',' ',$section->type))}}</div><div class="hp-status"><span class="hp-pill {{$section->is_active?'':'off'}}">{{$section->is_active?'Visible':'Hidden'}}</span></div>
  <div class="hp-row-actions"><a class="hp-btn" href="{{route('admin.homepage.edit',$section)}}"><i class="fa fa-pen"></i> Edit</a><form method="post" action="{{route('admin.homepage.destroy',$section)}}" onsubmit="return confirm('Remove this homepage section?')">@csrf @method('DELETE')<button class="hp-btn text-danger"><i class="fa fa-trash"></i></button></form></div>
 </div>@empty<div class="hp-empty"><h3>Create your homepage</h3><p>Add a header carousel, steps, gallery or testimonials.</p><a class="hp-btn primary" href="{{route('admin.homepage.create')}}">Add first section</a></div>@endforelse
 </div>
</div>
