<style>.am{--line:#e1e8f1;--ink:#17233c;--muted:#71809a;max-width:100%}.am-head{margin-bottom:20px}.am-head h1{margin:0 0 5px;color:var(--ink);font-size:28px}.am-head p{margin:0;color:var(--muted)}.am-card{padding:24px;border:1px solid var(--line);border-radius:15px;background:#fff;box-shadow:0 8px 24px rgba(33,55,90,.05)}.am-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:17px}.am-field.full{grid-column:1/-1}.am-field label{display:block;margin-bottom:7px;color:#34445d;font-size:12px;font-weight:750}.am-field input,.am-field select{width:100%;height:44px;border:1px solid #d8e0ec;border-radius:9px;padding:0 12px}.am-categories{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.am-check{display:flex!important;align-items:center;gap:8px;margin:0!important;padding:10px;border:1px solid #d8e0ec;border-radius:9px}.am-check input{width:16px;height:16px}.am-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:22px}.am-btn{display:inline-flex;align-items:center;justify-content:center;height:42px;padding:0 17px;border:1px solid #d8e0ec;border-radius:9px;background:#fff;color:#40506b;text-decoration:none;font-weight:750}.am-btn.primary{border-color:#397cf6;background:#397cf6;color:#fff}@media(max-width:750px){.am-grid{grid-template-columns:1fr}.am-field.full{grid-column:auto}.am-categories{grid-template-columns:1fr}}</style>
<div class="am"><div class="am-head"><h1>Add business member</h1><p>The account and first business are activated immediately. The member can sign in with mobile OTP.</p></div>
@if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif
<form class="am-card" method="post">@csrf<div class="am-grid">
<div class="am-field"><label>First name *</label><input name="first_name" value="{{old('first_name')}}" required></div><div class="am-field"><label>Last name</label><input name="last_name" value="{{old('last_name')}}"></div>
<div class="am-field"><label>Email *</label><input type="email" name="email" value="{{old('email')}}" required></div><div class="am-field"><label>Mobile *</label><input name="mobile" inputmode="numeric" maxlength="10" value="{{old('mobile')}}" required></div>
<div class="am-field full"><label>Business name *</label><input name="business_name" value="{{old('business_name')}}" required></div><div class="am-field full"><label>Business categories *</label><div class="am-categories">@foreach($categories as $category)<label class="am-check"><input type="checkbox" name="category_ids[]" value="{{$category->bcm_id}}" @checked(in_array($category->bcm_id,old('category_ids',[])))><span>{{$category->name}}</span></label>@endforeach</div></div>
<div class="am-field full"><label>Address line 1</label><input name="address_line_1" value="{{old('address_line_1')}}"></div><div class="am-field"><label>City</label><input name="city" value="{{old('city')}}"></div><div class="am-field"><label>Country *</label><select id="country" name="country" required><option value="">Select country</option>@foreach($countries as $country)<option value="{{$country->id}}" @selected((string)old('country',$defaultCountryId)===(string)$country->id)>{{$country->name}}</option>@endforeach</select></div><div class="am-field"><label>State *</label><select id="state" name="state" data-selected="{{old('state')}}" required><option value="">Select a country first</option></select></div><div class="am-field"><label>PIN code *</label><input name="pincode" maxlength="6" value="{{old('pincode')}}" required></div>
</div><div class="am-actions"><a class="am-btn" href="{{route('admin.clients.registered-members')}}">Cancel</a><button class="am-btn primary">Create member</button></div></form></div>
<script>(()=>{const c=document.getElementById('country'),s=document.getElementById('state'),selected=s.dataset.selected;async function load(){if(!c.value){s.innerHTML='<option value="">Select a country first</option>';return}const r=await fetch(`{{url('/api/v1/utilities/countries')}}/${c.value}/states`,{headers:{Accept:'application/json'}});if(!r.ok)return;const rows=await r.json();s.innerHTML='<option value="">Select state</option>'+rows.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');if(selected)s.value=selected}c.addEventListener('change',load);load()})()</script>
