<style>.cf{max-width:1050px;color:#18243a}.cf-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:20px}.cf-card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden}.cf-title{padding:16px 20px;border-bottom:1px solid #e2e8f0;font-weight:800;font-size:18px}.cf-body{padding:20px;display:grid;grid-template-columns:1fr 1fr;gap:17px}.cf label{font-size:13px;font-weight:700;margin-bottom:6px}.cf .full{grid-column:1/-1}.cf-actions{padding:16px 20px;border-top:1px solid #e2e8f0;display:flex;justify-content:flex-end;gap:10px}@media(max-width:700px){.cf-body{grid-template-columns:1fr}.cf .full{grid-column:auto}}</style>
<div class="cf"><div class="cf-head"><div><div class="text-primary">Chapters / {{$chapter->exists?'Edit':'Create'}}</div><h1 class="h2 fw-bold mb-0">{{$chapter->exists?'Edit chapter':'Create a chapter'}}</h1><div class="text-muted">Set the identity, location and regular meeting schedule.</div></div><a class="btn btn-outline-secondary" href="{{$chapter->exists?route('admin.chapters.show',$chapter):route('admin.chapters.index')}}">Back</a></div>
<form method="post" action="{{$chapter->exists?route('admin.chapters.update',$chapter):route('admin.chapters.store')}}">@csrf @if($chapter->exists)@method('put')@endif
<div class="cf-card"><div class="cf-title">Chapter information</div><div class="cf-body">
<div><label>Chapter name *</label><input class="form-control" name="name" value="{{old('name',$chapter->name)}}" required>@error('name')<small class="text-danger">{{$message}}</small>@enderror</div>
<div><label>Unique code *</label><input class="form-control" name="code" value="{{old('code',$chapter->code)}}" placeholder="NW-KOL-01" required>@error('code')<small class="text-danger">{{$message}}</small>@enderror</div>
<div><label>City</label><input class="form-control" name="city" value="{{old('city',$chapter->city)}}"></div><div><label>Meeting venue</label><input class="form-control" name="venue" value="{{old('venue',$chapter->venue)}}"></div>
<div><label>Meeting day</label><select class="form-select" name="meeting_day"><option value="">Not scheduled</option>@foreach(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'] as $d)<option @selected(old('meeting_day',$chapter->meeting_day)===$d)>{{$d}}</option>@endforeach</select></div><div><label>Meeting time</label><input class="form-control" type="time" name="meeting_time" value="{{old('meeting_time',$chapter->meeting_time ? substr($chapter->meeting_time,0,5):'')}}"></div>
<div><label>Established on</label><input class="form-control" type="date" name="established_on" value="{{old('established_on',$chapter->established_on?->format('Y-m-d'))}}"></div><div><label>Status *</label><select class="form-select" name="status">@foreach(['forming','active','paused','closed'] as $s)<option value="{{$s}}" @selected(old('status',$chapter->status)===$s)>{{ucfirst($s)}}</option>@endforeach</select></div>
<div class="full"><label>Chapter description</label><textarea class="form-control" rows="4" name="description">{{old('description',$chapter->description)}}</textarea></div></div><div class="cf-actions"><a class="btn btn-outline-secondary" href="{{route('admin.chapters.index')}}">Cancel</a><button class="btn btn-primary px-4">{{$chapter->exists?'Save changes':'Create chapter'}}</button></div></div></form></div>
