<style>.cf{max-width:1050px;color:#18243a}.cf-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:20px}.cf-card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden}.cf-title{padding:16px 20px;border-bottom:1px solid #e2e8f0;font-weight:800;font-size:18px}.cf-body{padding:20px;display:grid;grid-template-columns:1fr 1fr;gap:17px}.cf label{font-size:13px;font-weight:700;margin-bottom:6px}.cf .full{grid-column:1/-1}.cf-help{display:block;margin-top:5px;color:#718096;font-size:12px}.cf-actions{padding:16px 20px;border-top:1px solid #e2e8f0;display:flex;justify-content:flex-end;gap:10px}.meeting-panel{grid-column:1/-1;display:grid;grid-template-columns:1fr 1fr;gap:17px;padding:17px;border:1px solid #dce6f3;border-radius:10px;background:#f8fbff}.is-hidden{display:none!important}@media(max-width:700px){.cf-body,.meeting-panel{grid-template-columns:1fr}.cf .full,.meeting-panel{grid-column:auto}}</style>
<div class="cf"><div class="cf-head"><div><div class="text-primary">Chapters / {{$chapter->exists?'Edit':'Create'}}</div><h1 class="h2 fw-bold mb-0">{{$chapter->exists?'Edit chapter':'Create a chapter'}}</h1><div class="text-muted">Set the identity, meeting schedule and location.</div></div><a class="btn btn-outline-secondary" href="{{$chapter->exists?route('admin.chapters.show',$chapter):route('admin.chapters.index')}}">Back</a></div>
@if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif
<form method="post" action="{{$chapter->exists?route('admin.chapters.update',$chapter):route('admin.chapters.store')}}">@csrf @if($chapter->exists)@method('put')@endif
<div class="cf-card"><div class="cf-title">Chapter information</div><div class="cf-body">
<div><label>Chapter name *</label><input class="form-control" name="name" value="{{old('name',$chapter->name)}}" required></div>
<div><label>Unique code *</label><input class="form-control" name="code" value="{{old('code',$chapter->code)}}" placeholder="NW-KOL-01" required></div>
<div><label>City</label><input class="form-control" name="city" value="{{old('city',$chapter->city)}}"></div>
<div><label>Established on</label><input class="form-control" type="date" name="established_on" value="{{old('established_on',$chapter->established_on?->format('Y-m-d'))}}"></div>
<div><label>Regular meeting *</label><select class="form-select" id="meetingFrequency" name="meeting_frequency" required>@foreach(['not_scheduled'=>'Not scheduled','weekly'=>'Weekly','monthly'=>'Monthly','twice_monthly'=>'Twice monthly'] as $value=>$label)<option value="{{$value}}" @selected(old('meeting_frequency',$chapter->meeting_frequency??'not_scheduled')===$value)>{{$label}}</option>@endforeach</select></div>
<div><label>Status *</label><select class="form-select" name="status">@foreach(['forming','active','paused','closed'] as $s)<option value="{{$s}}" @selected(old('status',$chapter->status)===$s)>{{ucfirst($s)}}</option>@endforeach</select></div>
<div class="meeting-panel" id="meetingPanel">
<div id="weeklyField"><label>Meeting weekday *</label><select class="form-select" name="meeting_day"><option value="">Choose a day</option>@foreach(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'] as $d)<option @selected(old('meeting_day',$chapter->meeting_day)===$d)>{{$d}}</option>@endforeach</select></div>
<div id="monthlyField"><label>Day of each month *</label><input class="form-control" type="number" min="1" max="31" name="meeting_day_of_month" value="{{old('meeting_day_of_month',$chapter->meeting_day_of_month)}}"><small class="cf-help">For shorter months, use the month's last available day.</small></div>
<div id="secondMonthlyField"><label>Second day of each month *</label><input class="form-control" type="number" min="1" max="31" name="meeting_second_day_of_month" value="{{old('meeting_second_day_of_month',$chapter->meeting_second_day_of_month)}}"></div>
<div><label>Meeting time *</label><input class="form-control" type="time" name="meeting_time" value="{{old('meeting_time',$chapter->meeting_time ? substr($chapter->meeting_time,0,5):'')}}"></div>
<div><label>Meeting type *</label><select class="form-select" id="meetingMode" name="meeting_mode"><option value="offline" @selected(old('meeting_mode',$chapter->meeting_mode)==='offline')>Offline / in person</option><option value="online" @selected(old('meeting_mode',$chapter->meeting_mode)==='online')>Online</option></select></div>
<div class="full" id="meetingAddressField"><label>Chapter meeting address *</label><textarea class="form-control" rows="3" name="meeting_address" placeholder="Building, street, area, city and postal code">{{old('meeting_address',$chapter->meeting_address??$chapter->venue)}}</textarea></div>
<div class="full" id="meetingLinkField"><label>Online meeting link *</label><input class="form-control" type="url" name="meeting_link" value="{{old('meeting_link',$chapter->meeting_link)}}" placeholder="https://meet.example.com/chapter"><small class="cf-help">Use a complete HTTPS link for Zoom, Google Meet, Teams, or another platform.</small></div>
</div>
<div class="full"><label>Chapter description</label><textarea class="form-control" rows="4" name="description">{{old('description',$chapter->description)}}</textarea></div></div><div class="cf-actions"><a class="btn btn-outline-secondary" href="{{route('admin.chapters.index')}}">Cancel</a><button class="btn btn-primary px-4">{{$chapter->exists?'Save changes':'Create chapter'}}</button></div></div></form></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const frequency=document.getElementById('meetingFrequency'),mode=document.getElementById('meetingMode'),panel=document.getElementById('meetingPanel'),weekly=document.getElementById('weeklyField'),monthly=document.getElementById('monthlyField'),second=document.getElementById('secondMonthlyField'),address=document.getElementById('meetingAddressField'),link=document.getElementById('meetingLinkField');function sync(){const f=frequency.value,scheduled=f!=='not_scheduled';panel.classList.toggle('is-hidden',!scheduled);weekly.classList.toggle('is-hidden',f!=='weekly');monthly.classList.toggle('is-hidden',!['monthly','twice_monthly'].includes(f));second.classList.toggle('is-hidden',f!=='twice_monthly');address.classList.toggle('is-hidden',mode.value!=='offline');link.classList.toggle('is-hidden',mode.value!=='online')}frequency.addEventListener('change',sync);mode.addEventListener('change',sync);sync()});</script>
