<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{$title}}</title><link href="<?= env('UPLOADS_URL').$generalSetting->site_favicon ?>" rel="icon"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">@include('front.partials.cms-styles')
<style>*{box-sizing:border-box}.guest-page{min-height:72vh;padding:52px 20px 76px;background:#f5f7fb}.guest-shell{max-width:760px;margin:auto}.guest-head h1{margin:0 0 10px;color:#172640;font-size:36px}.guest-head p{margin:0 0 24px;color:#687990;line-height:1.65}.guest-card{overflow:hidden;border:1px solid #e1e7f0;border-radius:16px;background:#fff;box-shadow:0 16px 45px rgba(28,49,84,.08)}.guest-section{padding:28px 30px}.steps{display:flex;gap:8px;margin-bottom:22px}.step{flex:1;padding:9px;border-radius:8px;background:#edf1f7;color:#71809a;text-align:center;font-size:12px;font-weight:800}.step.active{background:#e8f1ff;color:#397ef6}.grid{display:grid;grid-template-columns:1fr 1fr;gap:17px}.field.full{grid-column:1/-1}.field label{display:block;margin-bottom:7px;color:#34445d;font-size:13px;font-weight:700}.input{width:100%;min-height:46px;padding:10px 13px;border:1px solid #d8e0eb;border-radius:9px;font:inherit}.button{display:inline-flex;min-height:45px;align-items:center;justify-content:center;margin-top:20px;padding:0 20px;border:0;border-radius:9px;background:#397ef6;color:#fff;font:inherit;font-weight:800;cursor:pointer}.alert{margin-bottom:18px;padding:14px 16px;border-radius:9px}.success{background:#e8f8f0;color:#13784b}.danger{background:#fff0f1;color:#a82d38}.mobile-note{padding:12px 14px;border-radius:9px;background:#f4f7fb;color:#52627a}.consent{display:flex;gap:9px;grid-column:1/-1;color:#56667e;font-size:13px}@media(max-width:650px){.grid{grid-template-columns:1fr}.field.full,.consent{grid-column:auto}.guest-section{padding:23px 20px}}</style></head><body>
@include('front.partials.cms-header')
<main class="guest-page"><div class="guest-shell"><header class="guest-head"><h1>Register as a guest</h1><p>Verify your mobile number, then complete your profile. Registered guests can view business contact details and connect with listed businesses.</p></header>
@if(session('success'))<div class="alert success">{{session('success')}}</div>@endif @if($errors->any())<div class="alert danger">{{$errors->first()}}</div>@endif
<div class="steps"><div class="step {{!$guestMobile?'active':''}}">1. Mobile</div><div class="step {{$guestMobile&&!$guestVerified?'active':''}}">2. Verify OTP</div><div class="step {{$guestVerified?'active':''}}">3. Profile</div></div>
<section class="guest-card"><div class="guest-section">
@if(!$guestMobile)
<form method="post" action="{{route('guest.register.send-otp')}}">@csrf<div class="field"><label>Mobile number *</label><input class="input" name="mobile" inputmode="numeric" maxlength="10" value="{{old('mobile')}}" placeholder="10-digit mobile number" required></div><button class="button">Send OTP</button></form>
@elseif(!$guestVerified)
<div class="mobile-note">OTP sent to mobile number ending in {{substr($guestMobile,-4)}}.</div><form method="post" action="{{route('guest.register.verify-otp')}}">@csrf<div class="field" style="margin-top:18px"><label>4-digit OTP *</label><input class="input" name="otp" inputmode="numeric" maxlength="4" autocomplete="one-time-code" required></div><button class="button">Verify mobile</button></form>
@else
<form method="post" action="{{route('guest.register.complete')}}">@csrf<div class="grid">
<div class="field"><label>Title</label><select class="input" name="salutation"><option value="">Select title</option>@foreach(['Mr.','Mrs.','Ms.','Miss','Dr.','Prof.','Mx.'] as $title)<option value="{{$title}}" @selected(old('salutation')===$title)>{{$title}}</option>@endforeach</select></div><div class="field"><label>First name *</label><input class="input" name="first_name" value="{{old('first_name')}}" required></div><div class="field"><label>Last name</label><input class="input" name="last_name" value="{{old('last_name')}}"></div>
<div class="field full"><label>Email address *</label><input class="input" type="email" name="email" value="{{old('email')}}" required></div>
<div class="field"><label>Country *</label><select class="input" id="country" name="country" required><option value="">Select country</option>@foreach($countries as $country)<option value="{{$country->id}}" @selected((string)old('country',$defaultCountryId)===(string)$country->id)>{{$country->name}}</option>@endforeach</select></div>
<div class="field"><label>State *</label><select class="input" id="state" name="state" data-selected="{{old('state')}}" required><option value="">Select a country first</option></select></div>
<label class="consent"><input type="checkbox" name="consent" value="1" required><span>I confirm that these details are correct.</span></label></div><button class="button">Complete guest registration</button></form>
@endif
</div></section></div></main>@include('front.partials.cms-footer')
@if($guestVerified)<script>(()=>{const c=document.getElementById('country'),s=document.getElementById('state'),selected=s.dataset.selected;async function load(){if(!c.value){s.innerHTML='<option value="">Select a country first</option>';return}const r=await fetch(`{{url('/api/v1/utilities/countries')}}/${c.value}/states`,{headers:{Accept:'application/json'}});if(!r.ok)return;const rows=await r.json();s.innerHTML='<option value="">Select state</option>'+rows.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');if(selected)s.value=selected}c.addEventListener('change',load);load()})()</script>@endif
</body></html>
