<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{$title}}</title><link href="<?= env('UPLOADS_URL').$generalSetting->site_favicon ?>" rel="icon"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">@include('front.partials.cms-styles')
<style>.join-page{background:#f5f7fb;min-height:70vh;padding:48px 22px 76px}.join-shell{max-width:850px;margin:auto}.join-head{margin-bottom:26px}.join-head h1{margin:9px 0;color:#172640;font-size:36px}.join-head p{color:#687990;line-height:1.7}.join-card{background:#fff;border:1px solid #e1e7f0;border-radius:16px;box-shadow:0 16px 45px rgba(28,49,84,.08);overflow:hidden}.join-section{padding:28px 30px;border-bottom:1px solid #e9edf3}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.field.full{grid-column:1/-1}.field label{display:block;margin-bottom:7px;color:#34445d;font-size:13px;font-weight:700}.input{box-sizing:border-box;width:100%;min-height:45px;padding:10px 13px;border:1px solid #d8e0eb;border-radius:9px;font:inherit}.error{display:block;color:#c93642;font-size:12px;margin-top:5px}.alert{margin-bottom:20px;padding:16px 18px;border-radius:10px}.success{background:#e8f8f0;color:#13784b}.danger,.closed{background:#fff0f1;color:#a82d38}.submit{padding:13px 21px;border:0;border-radius:9px;background:#397ef6;color:#fff;font-weight:800}.consent{display:flex;gap:9px;color:#56667e;font-size:13px}.actions{display:flex;justify-content:space-between;align-items:center;gap:20px}.honeypot{position:absolute;left:-10000px}@media(max-width:700px){.form-grid{grid-template-columns:1fr}.field.full{grid-column:auto}.actions{align-items:stretch;flex-direction:column}.submit{width:100%}}</style></head><body>
<style>.join-section h2{margin-top:0}.section-note{margin:-8px 0 20px;color:#687990;font-size:13px;line-height:1.55}.business-toggle{display:flex;align-items:flex-start;gap:10px;color:#34445d;font-weight:700;cursor:pointer}.business-toggle input{width:18px;height:18px;margin-top:1px}.business-fields{margin-top:22px}.category-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.category-option{display:flex!important;align-items:center;gap:8px;margin:0!important;padding:10px;border:1px solid #d8e0eb;border-radius:9px;font-weight:600!important}.category-option input{width:17px;height:17px}textarea.input{resize:vertical}@media(max-width:700px){.category-list{grid-template-columns:1fr}}</style>
@include('front.partials.cms-header')
<main class="join-page"><div class="join-shell"><header class="join-head"><h1>Join Net-Works</h1><p>Register as a guest and sign in immediately using mobile OTP. If you include business details, the account and business will wait for administrator approval.</p></header>
@if(session('registration_success'))<div class="alert success"><strong>Registration received.</strong> Your registration number is <strong>{{session('registration_success')}}</strong>. {{session('registration_requires_approval') ? 'You can sign in after an administrator approves your business-member registration.' : 'You can now sign in using the OTP sent to your registered mobile number.'}}</div>@endif
@if($errors->any())<div class="alert danger"><strong>Please review the form.</strong> {{$errors->first()}}</div>@endif
@unless($registrationOpen)<div class="alert closed"><strong>Registration is currently closed.</strong><br>{{$registrationSettings->closed_message ?: 'Please contact the administrator for assistance.'}}</div>@else
<form class="join-card" method="post" action="{{route('join.store')}}">@csrf<div class="honeypot"><input name="website" tabindex="-1" autocomplete="off"></div>
<section class="join-section"><h2>Your details</h2><div class="form-grid">
<div class="field"><label>First name *</label><input class="input" name="first_name" value="{{old('first_name')}}" required>@error('first_name')<span class="error">{{$message}}</span>@enderror</div>
<div class="field"><label>Last name</label><input class="input" name="last_name" value="{{old('last_name')}}"></div>
<div class="field"><label>Email address *</label><input class="input" type="email" name="email" value="{{old('email')}}" required>@error('email')<span class="error">{{$message}}</span>@enderror</div>
<div class="field"><label>Mobile number *</label><input class="input" name="mobile" inputmode="numeric" maxlength="10" value="{{old('mobile')}}" required>@error('mobile')<span class="error">{{$message}}</span>@enderror</div>
<div class="field"><label>WhatsApp number</label><input class="input" name="whatsapp" inputmode="numeric" maxlength="10" value="{{old('whatsapp')}}"></div>
<div class="field full"><label>Address</label><input class="input" name="address_line_1" value="{{old('address_line_1')}}"></div>
<div class="field full"><label>Address line 2</label><input class="input" name="address_line_2" value="{{old('address_line_2')}}"></div>
<div class="field"><label>City</label><input class="input" name="city" value="{{old('city')}}"></div>
<div class="field"><label>Country</label><select class="input" id="country" name="country"><option value="">Select country</option>@foreach($countries as $country)<option value="{{$country->id}}" @selected((string)old('country',$defaultCountryId)===(string)$country->id)>{{$country->name}}</option>@endforeach</select></div>
<div class="field"><label>State</label><select class="input" id="state" name="state" data-selected="{{old('state')}}"><option value="">Select a country first</option></select></div>
<div class="field"><label>PIN code</label><input class="input" name="pincode" maxlength="6" value="{{old('pincode')}}"></div>
</div></section>
<section class="join-section"><h2>Business details</h2><p class="section-note">Optional. Complete this section only if you are registering a business. The business will remain pending until approved.</p><label class="business-toggle"><input type="checkbox" id="wantsBusiness" name="wants_business" value="1" @checked(old('wants_business'))><span>I want to register a business</span></label><div class="business-fields form-grid" id="businessFields" @if(!old('wants_business')) hidden @endif><div class="field full"><label>Business name *</label><input class="input" name="business_name" value="{{old('business_name')}}" data-business-required>@error('business_name')<span class="error">{{$message}}</span>@enderror</div><div class="field full"><label>Business categories *</label><div class="category-list">@foreach($businessCategories as $category)<label class="category-option"><input type="checkbox" name="category_ids[]" value="{{$category->bcm_id}}" @checked(in_array($category->bcm_id,old('category_ids',[])))><span>{{$category->name}}</span></label>@endforeach</div>@error('category_ids')<span class="error">{{$message}}</span>@enderror</div><div class="field"><label>Business email</label><input class="input" type="email" name="business_email" value="{{old('business_email')}}"></div><div class="field"><label>Business phone</label><input class="input" name="business_phone" maxlength="15" value="{{old('business_phone')}}"></div><div class="field full"><label>Short business description</label><textarea class="input" name="business_description" rows="4">{{old('business_description')}}</textarea></div></div></section>
<section class="join-section actions"><label class="consent"><input type="checkbox" name="consent" value="1" required><span>I confirm that the information is correct and may be used to create my member profile.</span></label><button class="submit">Submit registration</button></section></form>@endunless
</div></main>@include('front.partials.cms-footer')
@if($registrationOpen)<script>(()=>{const toggle=document.getElementById('wantsBusiness'),fields=document.getElementById('businessFields'),required=document.querySelector('[data-business-required]');if(!toggle||!fields)return;const sync=()=>{fields.hidden=!toggle.checked;required.required=toggle.checked};toggle.addEventListener('change',sync);sync()})()</script><script>(()=>{const c=document.getElementById('country'),s=document.getElementById('state');if(!c||!s)return;const selected=s.dataset.selected;async function load(){if(!c.value){s.innerHTML='<option value="">Select a country first</option>';return}const r=await fetch(`{{url('/api/v1/utilities/countries')}}/${c.value}/states`,{headers:{Accept:'application/json'}});if(!r.ok)return;const rows=await r.json();s.innerHTML='<option value="">Select state</option>'+rows.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');if(selected)s.value=selected}c.addEventListener('change',load);load()})()</script>@endif
</body></html>
