<?php
namespace Tests\Unit\Imports;
use App\Services\Imports\FlexibleUserBusinessImportService;
use Tests\TestCase;

class FlexibleUserBusinessImportServiceTest extends TestCase {
 public function test_it_reads_a_custom_header_row_and_maps_columns():void {$file=tempnam(sys_get_temp_dir(),'import').'.csv';file_put_contents($file,"Import generated by ERP\nMember Name,Email Address,Mobile Number,Company,GST\nAda Lovelace,ada@example.test,9999999999,Analytical Engines,19ABCDE1234F1Z5\n");$service=app(FlexibleUserBusinessImportService::class);$sheet=$service->read($file,2);$this->assertSame(['Member Name','Email Address','Mobile Number','Company','GST'],$sheet['headers']);$mapped=$service->mapped($sheet['rows'][0],['user.first_name'=>0,'user.email'=>1,'user.mobile'=>2,'business.name'=>3,'business.gst'=>4]);$this->assertSame('Analytical Engines',$mapped['business.name']);$this->assertSame([],$service->validateRow($mapped,'users_business'));@unlink($file);}
 public function test_it_reports_missing_required_fields():void {$errors=app(FlexibleUserBusinessImportService::class)->validateRow(['user.email'=>'not-an-email'],'users_business');$this->assertNotEmpty($errors);$this->assertStringContainsString('Business name',implode(' | ',$errors));}
}
