@include('admin.maincontents.membership.accounts.styles')
<div class="ma">
 <div class="ma-head"><div><nav><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{url('admin/dashboard')}}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{url('admin/memberships')}}">Memberships</a></li><li class="breadcrumb-item active">Accounts</li></ol></nav><h1>Membership Accounts</h1><div class="subtitle">Receivables, collections, advances and payment control</div></div><form class="d-flex gap-2"><input type="date" name="from" class="form-control" value="{{$filters['from']}}"><input type="date" name="to" class="form-control" value="{{$filters['to']}}"><button class="btn btn-primary btn-ma">Apply</button></form></div>
 <div class="kpis"><div class="kpi"><div class="kpi-label">Invoiced this period</div><div class="kpi-value">₹{{number_format((float)$stats['invoiced'],2)}}</div></div><div class="kpi"><div class="kpi-label">Collected</div><div class="kpi-value">₹{{number_format((float)$stats['collected'],2)}}</div></div><div class="kpi"><div class="kpi-label">Receivable</div><div class="kpi-value">₹{{number_format((float)$stats['receivable'],2)}}</div></div><div class="kpi danger"><div class="kpi-label">Overdue</div><div class="kpi-value">₹{{number_format((float)$stats['overdue'],2)}}</div></div><div class="kpi"><div class="kpi-label">Member advances</div><div class="kpi-value">₹{{number_format((float)$stats['advances'],2)}}</div></div><div class="kpi"><div class="kpi-label">Due in 30 days</div><div class="kpi-value">{{number_format($stats['due_30'])}}</div></div></div>
 <div class="grid-2">
  <section class="panel"><div class="panel-head"><h2>Overdue invoices</h2><span class="meta">Oldest due first</span></div><div class="table-responsive"><table class="table"><thead><tr><th>Member</th><th>Invoice</th><th>Due date</th><th class="text-end">Balance</th></tr></thead><tbody>@forelse($overdueInvoices as $invoice)@php $name=trim(($invoice->user->userDetail->ud_first_name??'').' '.($invoice->user->userDetail->ud_last_name??''))?:$invoice->user->um_user_name;@endphp<tr><td><a class="name" href="{{route('admin.membership-accounts.member',$invoice->user)}}">{{$name}}</a><div class="meta">{{$invoice->user->um_email_id}}</div></td><td>{{$invoice->invoice_number}}</td><td class="text-danger">{{$invoice->due_date?->format('d M Y')}}</td><td class="money">₹{{number_format((float)$invoice->balance_due,2)}}</td></tr>@empty<tr><td colspan="4" class="empty">No overdue invoices.</td></tr>@endforelse</tbody></table></div></section>
  <section class="panel"><div class="panel-head"><h2>Recent receipts</h2><span class="meta">Latest posted payments</span></div><div class="table-responsive"><table class="table"><thead><tr><th>Receipt / member</th><th>Method</th><th class="text-end">Amount</th></tr></thead><tbody>@forelse($recentPayments as $payment)@php $name=trim(($payment->user->userDetail->ud_first_name??'').' '.($payment->user->userDetail->ud_last_name??''))?:$payment->user->um_user_name;@endphp<tr><td><a class="name" href="{{route('admin.membership-accounts.receipt',$payment->receipt)}}">{{$payment->receipt?->receipt_number}}</a><div class="meta">{{$name}} · {{$payment->payment_date->format('d M Y')}}</div></td><td>{{ucwords(str_replace('_',' ',$payment->method))}}</td><td class="money">₹{{number_format((float)$payment->amount,2)}}</td></tr>@empty<tr><td colspan="3" class="empty">No payments posted yet.</td></tr>@endforelse</tbody></table></div></section>
 </div>
 <section class="panel mt-3"><div class="panel-head"><h2>Collection by payment method</h2></div><div class="panel-body d-flex flex-wrap gap-3">@forelse($methodTotals as $method=>$total)<div><div class="meta">{{strtoupper(str_replace('_',' ',$method))}}</div><div class="name">₹{{number_format((float)$total,2)}}</div></div>@empty<span class="meta">No collection in this period.</span>@endforelse</div></section>
</div>
