@include('admin.maincontents.membership.accounts.styles')
@php $displayName=trim(($user->userDetail->ud_first_name??'').' '.($user->userDetail->ud_last_name??''))?:($user->um_user_name?:'Member #'.$user->um_id); @endphp
<div class="ma">
 <div class="ma-head"><div><nav><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{url('admin/membership-accounts')}}">Accounts</a></li><li class="breadcrumb-item active">Member ledger</li></ol></nav><h1>{{$displayName}}</h1><div class="subtitle">{{$user->um_email_id}} · {{$user->um_mobile_no?:'No mobile'}} · {{$membership->plan?->name??'No plan'}}</div></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary btn-ma" href="{{url('admin/memberships/'.$user->um_id.'/edit')}}"><i class="fa fa-cog"></i> Membership</a><a class="btn btn-outline-primary btn-ma" href="{{route('admin.membership-accounts.invoice',$user)}}"><i class="fa fa-file-invoice"></i> New invoice</a><a class="btn btn-primary btn-ma" href="{{route('admin.membership-accounts.payment',$user)}}"><i class="fa fa-indian-rupee-sign"></i> Record payment</a></div></div>
 @if(session('success_message'))<div class="alert alert-success py-2 small">{{session('success_message')}}</div>@endif
 <div class="summary-strip"><div class="summary-cell"><span>Total billed</span><strong>₹{{number_format((float)$summary['billed'],2)}}</strong></div><div class="summary-cell"><span>Total received</span><strong>₹{{number_format((float)$summary['received'],2)}}</strong></div><div class="summary-cell"><span>Balance due</span><strong class="{{$summary['outstanding']>0?'text-danger':''}}">₹{{number_format((float)$summary['outstanding'],2)}}</strong></div><div class="summary-cell"><span>Advance</span><strong>₹{{number_format((float)$summary['advance'],2)}}</strong></div></div>
 <section class="panel"><div class="panel-head"><h2>Account ledger</h2><button type="button" onclick="window.print()" class="btn btn-sm btn-outline-secondary"><i class="fa fa-print me-1"></i>Print statement</button></div><div class="table-responsive"><table class="table"><thead><tr><th>Date</th><th>Document</th><th>Particulars</th><th class="text-end">Debit</th><th class="text-end">Credit</th><th class="text-end">Balance</th></tr></thead><tbody>@forelse($ledger as $entry)<tr><td>{{$entry['date']->format('d M Y')}}</td><td class="name">{{$entry['document']}}</td><td>{{$entry['description']}}</td><td class="money">{{$entry['debit']?'₹'.number_format($entry['debit'],2):'—'}}</td><td class="money">{{$entry['credit']?'₹'.number_format($entry['credit'],2):'—'}}</td><td class="money {{$entry['balance']>0?'text-danger':'text-success'}}">₹{{number_format(abs($entry['balance']),2)}} {{$entry['balance']>=0?'Dr':'Cr'}}</td></tr>@empty<tr><td colspan="6" class="empty">No accounting entries yet. Create the first invoice to begin this ledger.</td></tr>@endforelse</tbody></table></div></section>
 <div class="grid-2 mt-3"><section class="panel"><div class="panel-head"><h2>Invoices</h2><a href="{{route('admin.membership-accounts.invoice',$user)}}" class="btn btn-sm btn-outline-primary">Create</a></div><div class="table-responsive"><table class="table"><thead><tr><th>Invoice</th><th>Date / due</th><th>Status</th><th class="text-end">Total</th><th class="text-end">Balance</th></tr></thead><tbody>@forelse($invoices as $invoice)<tr><td class="name">{{$invoice->invoice_number?:'Draft #'.$invoice->id}}</td><td>{{$invoice->invoice_date->format('d M Y')}}<div class="meta">Due {{$invoice->due_date?->format('d M Y')?:'—'}}</div></td><td><span class="badge-soft {{$invoice->status==='paid'?'badge-paid':($invoice->status==='draft'?'badge-draft':'badge-open')}}">{{str_replace('_',' ',$invoice->status)}}</span></td><td class="money">₹{{number_format((float)$invoice->total_amount,2)}}</td><td class="money">₹{{number_format((float)$invoice->balance_due,2)}}</td></tr>@empty<tr><td colspan="5" class="empty">No invoices.</td></tr>@endforelse</tbody></table></div></section>
 <section class="panel"><div class="panel-head"><h2>Payments & receipts</h2><a href="{{route('admin.membership-accounts.payment',$user)}}" class="btn btn-sm btn-outline-primary">Record</a></div><div class="table-responsive"><table class="table"><thead><tr><th>Receipt</th><th>Date</th><th>Method</th><th class="text-end">Amount</th><th class="text-end">Advance</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>@if($payment->receipt)<a class="name" href="{{route('admin.membership-accounts.receipt',$payment->receipt)}}">{{$payment->receipt->receipt_number}}</a>@else {{$payment->payment_number}} @endif<div class="meta">{{$payment->reference}}</div></td><td>{{$payment->payment_date->format('d M Y')}}</td><td>{{ucwords(str_replace('_',' ',$payment->method))}}</td><td class="money">₹{{number_format((float)$payment->amount,2)}}</td><td class="money">₹{{number_format((float)$payment->unallocated_amount,2)}}</td></tr>@empty<tr><td colspan="5" class="empty">No posted payments.</td></tr>@endforelse</tbody></table></div></section></div>
</div>
