@php
use App\Models\GeneralSetting;
$settings=GeneralSetting::find(1);
$payment=$receipt->payment;
$user=$payment->user;
$displayName=trim(($user->userDetail->ud_first_name??'').' '.($user->userDetail->ud_last_name??''))?:$user->um_user_name;
@endphp
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{$receipt->receipt_number}} · Payment Receipt</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"><style>
*{box-sizing:border-box}body{margin:0;padding:30px;color:#25344d;background:#f4f6f9;font-family:Inter,sans-serif}.receipt{width:min(780px,100%);margin:auto;border:1px solid #dfe5ed;border-radius:10px;background:#fff;box-shadow:0 10px 35px rgba(25,40,65,.08);overflow:hidden}.head{display:flex;align-items:center;justify-content:space-between;padding:28px 34px;border-bottom:1px solid #e5eaf1}.head img{max-width:180px;max-height:55px}.head h1{margin:0;font-size:22px}.head p{margin:5px 0 0;color:#7a8798;font-size:12px}.body{padding:30px 34px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:25px;margin-bottom:28px}.label{color:#8591a2;font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:.06em}.value{margin-top:5px;font-size:13px;font-weight:600}.amount{margin:25px 0;padding:20px;border-radius:8px;color:#096b45;background:#ecfdf3;text-align:center}.amount span{display:block;font-size:10px;text-transform:uppercase;font-weight:700}.amount strong{display:block;margin-top:5px;font-size:30px}.alloc{width:100%;border-collapse:collapse;font-size:12px}.alloc th,.alloc td{padding:10px;border-bottom:1px solid #e8ecf2;text-align:left}.alloc th{color:#69778b;background:#f8fafc;font-size:9px;text-transform:uppercase}.alloc td:last-child,.alloc th:last-child{text-align:right}.foot{padding:18px 34px;color:#7f8b9c;background:#f8fafc;font-size:10px;text-align:center}.actions{display:flex;justify-content:center;gap:8px;margin:18px}.btn{padding:9px 14px;border:1px solid #ccd5e1;border-radius:6px;color:#34445d;background:#fff;font:600 12px Inter;text-decoration:none;cursor:pointer}.primary{color:#fff;border-color:#377dff;background:#377dff}@media print{body{padding:0;background:#fff}.receipt{width:100%;border:0;box-shadow:none}.actions{display:none}}
</style></head><body>
<div class="receipt"><div class="head"><div>@if($settings?->site_logo)<img src="<?=env('UPLOADS_URL').$settings->site_logo?>" alt="{{$settings->site_name}}">@else<h1>{{$settings->site_name??'Net-Works'}}</h1>@endif</div><div><h1>Payment Receipt</h1><p>{{$receipt->receipt_number}}</p></div></div><div class="body"><div class="meta"><div><div class="label">Received from</div><div class="value">{{$displayName}}</div><div>{{$user->um_email_id}} · {{$user->um_mobile_no}}</div></div><div><div class="label">Payment details</div><div class="value">{{$receipt->receipt_date->format('d M Y')}}</div><div>{{ucwords(str_replace('_',' ',$payment->method))}}{{$payment->reference?' · '.$payment->reference:''}}</div></div></div><div class="amount"><span>Amount received</span><strong>₹{{number_format((float)$receipt->amount,2)}}</strong></div><table class="alloc"><thead><tr><th>Allocated to</th><th>Amount</th></tr></thead><tbody>@forelse($payment->allocations as $allocation)<tr><td>{{$allocation->invoice->invoice_number}}</td><td>₹{{number_format((float)$allocation->amount,2)}}</td></tr>@empty<tr><td>Member advance / unallocated payment</td><td>₹{{number_format((float)$payment->amount,2)}}</td></tr>@endforelse</tbody></table></div><div class="foot">Computer-generated receipt. Posted as {{$payment->payment_number}} on {{$payment->posted_at->format('d M Y, h:i A')}}.</div></div><div class="actions"><a class="btn" href="{{route('admin.membership-accounts.member',$user)}}">Back to ledger</a><button class="btn primary" onclick="window.print()">Print receipt</button></div>
</body></html>
