<style>.ev-wrap{padding:22px 30px}.ev-head,.ev-toolbar,.ev-row{display:flex;align-items:center;justify-content:space-between;gap:16px}.ev-title{font-size:28px;font-weight:750;color:#16233a}.ev-sub{color:#718096}.ev-btn{border:1px solid #d7e0ee;border-radius:8px;padding:10px 16px;background:#fff;color:#334155;text-decoration:none;font-weight:650}.ev-btn.primary{background:#377dff;color:#fff;border-color:#377dff}.ev-card{border:1px solid #e3e9f2;border-radius:12px;background:#fff;margin-top:20px;overflow:hidden}.ev-toolbar{padding:14px 16px;border-bottom:1px solid #e8edf4}.ev-toolbar form{display:flex;gap:8px;flex:1}.ev-input{height:40px;border:1px solid #d7e0ee;border-radius:8px;padding:0 12px;min-width:180px}.ev-table{width:100%;border-collapse:collapse}.ev-table th{background:#f7f9fc;text-transform:uppercase;font-size:12px;color:#718096;text-align:left;padding:12px 14px}.ev-table td{padding:14px;border-top:1px solid #edf1f6;color:#53647a}.ev-name{font-weight:700;color:#1d2b42}.ev-pill{padding:4px 9px;border-radius:20px;font-size:12px;font-weight:700}.ev-pill.published{background:#def7ec;color:#087f5b}.ev-pill.draft{background:#edf1f6}.ev-empty{text-align:center;padding:55px;color:#718096}</style>
<div class="ev-wrap">
 <div class="ev-head"><div><div class="text-primary mb-1">Dashboard / Events</div><div class="ev-title">Event management</div><div class="ev-sub">Create events, sell seats, offer food and manage registrations.</div></div><a class="ev-btn primary" href="{{ route('admin.events.create') }}"><i class="fa fa-plus me-2"></i>Create event</a></div>
 <div class="ev-card"><div class="ev-toolbar"><form><input class="ev-input" name="search" value="{{ request('search') }}" placeholder="Search events"><select class="ev-input" name="status"><option value="">All statuses</option>@foreach(['draft','published','cancelled'] as $s)<option value="{{$s}}" @selected(request('status')===$s)>{{ucfirst($s)}}</option>@endforeach</select><button class="ev-btn primary">Apply</button></form><span>{{ $events->total() }} events</span></div>
 <div class="table-responsive"><table class="ev-table"><thead><tr><th>Event</th><th>Date & venue</th><th>Capacity</th><th>Orders</th><th>Revenue</th><th>Status</th><th>Actions</th></tr></thead><tbody>
 @forelse($events as $event)<tr><td><div class="ev-name">{{$event->title}}</div><small>/events/{{$event->slug}}</small></td><td>{{$event->starts_at->format('d M Y, h:i A')}}<br><small>{{$event->venue_name ?: 'Online / TBA'}}</small></td><td>{{$event->confirmed_seats}}{{is_null($event->capacity)?' / Unlimited':' / '.$event->capacity}}</td><td>{{$event->paid_orders_count}}</td><td>{{$event->currency}} {{number_format((float)($event->paid_revenue??0),2)}}</td><td><span class="ev-pill {{$event->status}}">{{ucfirst($event->status)}}</span></td><td style="white-space:nowrap"><a class="ev-btn" href="{{route('admin.events.preview',$event)}}" target="_blank" title="Preview public event page"><i class="fa fa-eye"></i> Preview</a> <a class="ev-btn" href="{{route('admin.events.edit',$event)}}">Edit</a> <a class="ev-btn" href="{{route('admin.events.orders',$event)}}">Orders</a></td></tr>
 @empty<tr><td colspan="7" class="ev-empty">No events yet. Create your first event to begin taking registrations.</td></tr>@endforelse
 </tbody></table></div><div class="p-3">{{$events->links()}}</div></div>
</div>
