<?php
namespace App\Services\Imports;
use App\Models\BulkImportJob;
use App\Models\Companies\CompaniesDetail;
use App\Models\Companies\CompaniesMaster;
use App\Models\User\UserDetails;
use App\Models\User\UserMaster;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use PhpOffice\PhpSpreadsheet\IOFactory;

class FlexibleUserBusinessImportService {
 public function fields(string $type):array {$user=['user.first_name'=>'First name *','user.last_name'=>'Last name','user.email'=>'Email *','user.mobile'=>'Mobile *','user.whatsapp'=>'WhatsApp','user.address1'=>'Address line 1','user.address2'=>'Address line 2','user.pincode'=>'PIN code'];$business=['business.name'=>'Business name *','business.email'=>'Business email','business.phone'=>'Business phone','business.whatsapp'=>'Business WhatsApp','business.gst'=>'GST number','business.pan'=>'PAN number','business.registration'=>'Registration number','business.description'=>'Description','business.address1'=>'Business address 1','business.address2'=>'Business address 2','business.address3'=>'Business address 3','business.pincode'=>'Business PIN code'];return $type==='users'?$user:($type==='businesses'?$business:$user+$business);}
 public function required(string $type):array{return $type==='users'?['user.first_name','user.email','user.mobile']:($type==='businesses'?['business.name']:['user.first_name','user.email','user.mobile','business.name']);}
 public function read(string $path,int $headerRow=1):array {if(strtolower(pathinfo($path,PATHINFO_EXTENSION))==='csv'){$lines=file($path,FILE_IGNORE_NEW_LINES);$sample=$lines[$headerRow-1]??'';$scores=[];foreach([',',';','\t','|'] as $delimiter)$scores[$delimiter]=count(str_getcsv($sample,$delimiter));arsort($scores);$reader=new \PhpOffice\PhpSpreadsheet\Reader\Csv();$reader->setDelimiter((string)array_key_first($scores));$book=$reader->load($path);}else{$book=IOFactory::load($path);}$sheet=$book->getActiveSheet()->toArray(null,true,true,false);$header=array_map(fn($v)=>trim((string)$v),$sheet[$headerRow-1]??[]);$rows=array_slice($sheet,$headerRow);$rows=array_values(array_filter($rows,fn($r)=>collect($r)->contains(fn($v)=>trim((string)$v)!=='')));return ['headers'=>$header,'rows'=>$rows];}
 public function mapped(array $row,array $mapping):array {$out=[];foreach($mapping as $target=>$column){if($column===''||$column===null)continue;$out[$target]=trim((string)($row[(int)$column]??''));}return $out;}
 public function validateRow(array $data,string $type):array {$errors=[];foreach($this->required($type) as $key)if(blank($data[$key]??null))$errors[]=$this->fields($type)[$key].' is missing';if(!blank($data['user.email']??null)&&!filter_var($data['user.email'],FILTER_VALIDATE_EMAIL))$errors[]='Invalid user email';if(!blank($data['business.email']??null)&&!filter_var($data['business.email'],FILTER_VALIDATE_EMAIL))$errors[]='Invalid business email';return $errors;}
 public function preview(BulkImportJob $job,int $limit=15):array {$data=$this->read(storage_path('app/'.$job->stored_path),$job->header_row);$out=[];foreach(array_slice($data['rows'],0,$limit) as $i=>$row){$mapped=$this->mapped($row,$job->mapping??[]);$out[]=['row'=>$job->header_row+$i+1,'data'=>$mapped,'errors'=>$this->validateRow($mapped,$job->type)];}return $out;}
 public function run(BulkImportJob $job):BulkImportJob {$source=$this->read(storage_path('app/'.$job->stored_path),$job->header_row);$stats=['created'=>0,'updated'=>0,'skipped'=>0];$errors=[];$update=(bool)($job->options['update_existing']??false);foreach($source['rows'] as $i=>$row){$line=$job->header_row+$i+1;$data=$this->mapped($row,$job->mapping??[]);$validation=$this->validateRow($data,$job->type);if($validation){$stats['skipped']++;$errors[]=['row'=>$line,'message'=>implode('; ',$validation),'data'=>$data];continue;}try{$result=DB::transaction(fn()=>$this->persist($data,$job->type,$update));$stats[$result]++;}catch(\Throwable $e){report($e);$stats['skipped']++;$errors[]=['row'=>$line,'message'=>$e->getMessage(),'data'=>$data];}}$job->update(['status'=>'completed','total_rows'=>count($source['rows']),'created_rows'=>$stats['created'],'updated_rows'=>$stats['updated'],'skipped_rows'=>$stats['skipped'],'errors'=>$errors,'completed_at'=>now()]);return $job->fresh();}
 private function persist(array $d,string $type,bool $update):string {$user=null;$business=null;$wasExisting=false;if($type!=='businesses'){$user=UserMaster::where(function($q)use($d){$q->where('um_email_id',$d['user.email'])->orWhere('um_mobile_no',$d['user.mobile']);})->first();$wasExisting=(bool)$user;if(!$user){$user=UserMaster::create(['um_utm_id'=>2,'um_email_id'=>$d['user.email'],'um_mobile_no'=>$d['user.mobile'],'um_status'=>1]);$id='EN'.str_pad($user->um_id,6,'0',STR_PAD_LEFT);$user->update(['um_user_name'=>$id,'um_password'=>Hash::make($id)]);}elseif(!$update)return 'skipped';$details=['ud_first_name'=>$d['user.first_name'],'ud_last_name'=>$d['user.last_name']??null,'ud_whatsapp_no'=>$d['user.whatsapp']??null,'ud_addr_1'=>$d['user.address1']??null,'ud_addr_2'=>$d['user.address2']??null,'ud_pincode'=>$d['user.pincode']??null];UserDetails::updateOrCreate(['ud_um_id'=>$user->um_id],$details);if($update)$user->update(['um_email_id'=>$d['user.email'],'um_mobile_no'=>$d['user.mobile']]);}
  if($type!=='users'){$detail=null;if(!blank($d['business.gst']??null))$detail=CompaniesDetail::where('cmpd_gst_no',$d['business.gst'])->first();if(!$detail&&!blank($d['business.email']??null))$detail=CompaniesDetail::where('cmpd_email',$d['business.email'])->first();if(!$detail)$detail=CompaniesDetail::where('cmpd_name',$d['business.name'])->where('cmpd_phone',$d['business.phone']??null)->first();if($detail){$business=CompaniesMaster::find($detail->cmpd_cmp_id);$wasExisting=true;if(!$update&&$type==='businesses')return 'skipped';}else{$business=CompaniesMaster::create([]);}$values=['cmpd_name'=>$d['business.name'],'cmpd_email'=>$d['business.email']??null,'cmpd_phone'=>$d['business.phone']??null,'cmpd_whatsapp_no'=>$d['business.whatsapp']??null,'cmpd_gst_no'=>$d['business.gst']??null,'cmpd_pan_no'=>$d['business.pan']??null,'cmpd_company_regn_no'=>$d['business.registration']??null,'cmpd_description'=>$d['business.description']??null,'cmpd_address1'=>$d['business.address1']??null,'cmpd_address2'=>$d['business.address2']??null,'cmpd_address3'=>$d['business.address3']??null,'cmpd_pincode'=>$d['business.pincode']??null,'cmpd_status'=>1];CompaniesDetail::updateOrCreate(['cmpd_cmp_id'=>$business->cmp_id],$values);if($user)$user->companies()->syncWithoutDetaching([$business->cmp_id]);}return $wasExisting?'updated':'created';}
}
