<?php
namespace App\Http\Controllers;

use App\Models\Events\Event;
use App\Models\Events\EventOrder;
use App\Services\Events\EventRegistrationService;
use App\Services\Events\StripeEventCheckoutService;
use Illuminate\Http\Request;

class EventPortalController extends Controller
{
 public function index(){ $events=Event::where('status','published')->where('ends_at','>=',now())->orderBy('starts_at')->paginate(12);return view('events.index',compact('events')); }
 public function show(Event $event){abort_unless($event->status==='published',404);$event->load(['tickets'=>fn($q)=>$q->where('is_active',1),'addons'=>fn($q)=>$q->where('is_active',1),'fields']);[$canRegister,$accessMessage]=$this->registrationAccess($event);return view('events.show',compact('event','canRegister','accessMessage'));}
 public function register(Request $request,Event $event,EventRegistrationService $registration,StripeEventCheckoutService $stripe){[$canRegister,$accessMessage]=$this->registrationAccess($event);if(!$canRegister)return back()->withInput()->withErrors(['registration'=>$accessMessage]);$isOpenEvent=!$event->requires_login;if($isOpenEvent){$ticket=$event->tickets()->where('is_active',1)->find((int)$request->input('ticket_id'));if(!$ticket)return back()->withInput()->withErrors(['registration'=>'Please choose an available admission option.']);$request->merge(['tickets'=>[$ticket->id=>1],'attendees'=>[]]);}$seatCount=collect($request->input('tickets',[]))->sum(fn($q)=>(int)$q);$rules=['customer_name'=>'required|string|max:255','customer_email'=>'required|email|max:255','customer_phone'=>'nullable|string|max:30','company_name'=>'required|string|max:255','gst_number'=>['nullable','string','max:30','regex:/^[A-Za-z0-9 -]+$/'],'tickets'=>'required|array','tickets.*'=>'nullable|integer|min:0','addons'=>'nullable|array','addons.*'=>'nullable|integer|min:0','attendees'=>'nullable|array','responses'=>'nullable|array'];if(!$isOpenEvent&&$event->collect_attendee_details){$rules['attendees']=['required','array','size:'.$seatCount];$rules['attendees.*.first_name']='required|string|max:100';$rules['attendees.*.company_name']='required|string|max:255';$rules['attendees.*.designation']='required|string|max:150';$rules['attendees.*.email']='nullable|email|max:255';$rules['attendees.*.phone']='nullable|string|max:30';}foreach($event->fields()->where('is_required',1)->where('applies_to','order')->get() as $field)$rules['responses.'.$field->field_key]=['required'];$data=$request->validate($rules,['attendees.size'=>'Please enter details for every selected attendee.']);try{$order=$registration->createOrder($event,$data);if((float)$order->total_amount<=0)return redirect()->route('events.confirmation',[$order,$order->confirmation_token]);return redirect()->away($stripe->create($order));}catch(\Throwable $e){report($e);return back()->withInput()->withErrors(['registration'=>$e->getMessage()]);}}
 public function success(Request $request,EventOrder $order,StripeEventCheckoutService $stripe){try{if(!$request->filled('session_id')||!$stripe->verify($order,$request->session_id))return redirect()->route('events.show',$order->event->slug)->withErrors(['payment'=>'Payment could not be verified.']);return redirect()->route('events.confirmation',[$order,$order->confirmation_token]);}catch(\Throwable $e){report($e);return redirect()->route('events.show',$order->event->slug)->withErrors(['payment'=>'Payment verification failed. Please contact support with order '.$order->order_number.'.']);}}
 public function confirmation(EventOrder $order,string $token){abort_unless($order->status==='paid'&&hash_equals($order->confirmation_token,$token),403);$order->load(['event','items','attendees']);return view('events.confirmation',compact('order'));}
 private function registrationAccess(Event $event):array {if(!$event->requires_login)return [true,null];$user=auth('member')->user();if(!$user)return [false,'Please sign in as an eligible member to register for this event.'];if(!in_array((int)$user->um_utm_id,array_map('intval',$event->allowed_user_types??[]),true))return [false,'This event is not available for your member type.'];return [true,null];}
}
