<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\BulkImportJob;
use App\Services\Imports\FlexibleUserBusinessImportService;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class BulkImportController extends Controller {
 public function index(){ $jobs=BulkImportJob::latest()->limit(20)->get();echo $this->admin_after_login_layout('Bulk Import','imports.index',compact('jobs')); }
 public function upload(Request $r,FlexibleUserBusinessImportService $service){$d=$r->validate(['type'=>'required|in:users,businesses,users_business','file'=>'required|file|mimes:xlsx,xls,csv|max:10240','header_row'=>'required|integer|min:1|max:25']);$name=Str::uuid().'.'.$r->file('file')->getClientOriginalExtension();$path=$r->file('file')->storeAs('imports',$name);try{$sheet=$service->read(storage_path('app/'.$path),(int)$d['header_row']);if(!$sheet['headers'])throw new \RuntimeException('No column headers were found.');}catch(\Throwable $e){@unlink(storage_path('app/'.$path));return back()->withErrors(['file'=>'The spreadsheet could not be read: '.$e->getMessage()]);}$mapping=$this->autoMap($sheet['headers'],$service->fields($d['type']));$job=BulkImportJob::create(['type'=>$d['type'],'original_name'=>$r->file('file')->getClientOriginalName(),'stored_path'=>$path,'header_row'=>$d['header_row'],'headers'=>$sheet['headers'],'mapping'=>$mapping,'total_rows'=>count($sheet['rows']),'created_by'=>auth('admin')->id()]);return redirect()->route('admin.imports.map',$job);}
 public function map(Request $r,BulkImportJob $job,FlexibleUserBusinessImportService $service){$fields=$service->fields($job->type);if($r->isMethod('post')){$mapping=array_filter($r->input('mapping',[]),fn($v)=>$v!=='');$missing=array_diff($service->required($job->type),array_keys($mapping));if($missing)return back()->withErrors(['mapping'=>'Map all required fields: '.implode(', ',array_map(fn($k)=>$fields[$k],$missing))])->withInput();$job->update(['mapping'=>$mapping,'options'=>['update_existing'=>$r->boolean('update_existing')],'status'=>'mapped']);}$preview=$service->preview($job);echo $this->admin_after_login_layout('Map Import Columns','imports.map',compact('job','fields','preview'));}
 public function run(BulkImportJob $job,FlexibleUserBusinessImportService $service){abort_unless($job->mapping,422);$job->update(['status'=>'processing']);$service->run($job);return redirect()->route('admin.imports.map',$job)->with('success_message','Import completed.');}
 public function errors(BulkImportJob $job){$rows=[['Row','Error','Imported data']];foreach($job->errors??[] as $error)$rows[]=[$error['row'],$error['message'],json_encode($error['data'],JSON_UNESCAPED_UNICODE)];return response()->streamDownload(function()use($rows){$out=fopen('php://output','w');foreach($rows as $row)fputcsv($out,$row);fclose($out);},'import-errors-'.$job->id.'.csv',['Content-Type'=>'text/csv']);}
 public function template(){ $rows=[['First Name','Last Name','Email','Mobile','WhatsApp','Business Name','Business Email','Business Phone','GST Number','PAN Number','Registration Number','Business Address','PIN Code'],['Amit','Sen','amit@example.com','9876543210','9876543210','Example Trading Pvt Ltd','accounts@example.com','03340000000','19ABCDE1234F1Z5','ABCDE1234F','CIN12345','Kolkata','700001']];return response()->streamDownload(function()use($rows){$out=fopen('php://output','w');foreach($rows as $row)fputcsv($out,$row);fclose($out);},'user-business-import-template.csv',['Content-Type'=>'text/csv']);}
 private function autoMap(array $headers,array $fields):array {$mapping=[];foreach($fields as $key=>$label){$needles=[strtolower(preg_replace('/[^a-z0-9]/i','',$label)),strtolower(preg_replace('/[^a-z0-9]/i','',last(explode('.',$key))))];foreach($headers as $i=>$header){$clean=strtolower(preg_replace('/[^a-z0-9]/i','',(string)$header));if($clean&&in_array($clean,$needles,true)){$mapping[$key]=(string)$i;break;}}}return $mapping;}
}
