<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\Events\Event;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class EventController extends Controller {
 public function index(Request $r){$q=Event::withCount(['orders as paid_orders_count'=>fn($x)=>$x->where('status','paid')])->withSum(['orders as paid_revenue'=>fn($x)=>$x->where('status','paid')],'total_amount');if($r->filled('status'))$q->where('status',$r->status);if($r->filled('search'))$q->where('title','like','%'.trim($r->search).'%');$events=$q->orderByDesc('starts_at')->paginate(20)->withQueryString();echo $this->admin_after_login_layout('Events','events.index',compact('events'));}
 public function create(Request $r){$event=new Event;if($r->isMethod('post'))return $this->save($r,$event);echo $this->admin_after_login_layout('Create Event','events.form',compact('event'));}
 public function edit(Request $r,Event $event){$event->load(['tickets','addons','fields']);if($r->isMethod('post'))return $this->save($r,$event);echo $this->admin_after_login_layout('Edit Event','events.form',compact('event'));}
 public function preview(Event $event){$event->load(['tickets'=>fn($q)=>$q->where('is_active',1),'addons'=>fn($q)=>$q->where('is_active',1),'fields']);$isPreview=true;return view('events.show',compact('event','isPreview'));}
 public function updateCover(Request $r,Event $event){$data=$r->validate(['cover_image'=>'nullable|required_without:remove_cover_image|image|mimes:jpg,jpeg,png,webp|max:5120','remove_cover_image'=>'nullable|boolean']);$old=$event->cover_image;if($r->hasFile('cover_image')){$dir=public_path('uploads/events');if(!is_dir($dir))mkdir($dir,0775,true);$name=Str::uuid().'.'.$r->file('cover_image')->extension();$r->file('cover_image')->move($dir,$name);$event->update(['cover_image'=>'uploads/events/'.$name]);}elseif($r->boolean('remove_cover_image')){$event->update(['cover_image'=>null]);}if($old&&$old!==$event->fresh()->cover_image&&str_starts_with($old,'uploads/events/')&&is_file(public_path($old)))@unlink(public_path($old));return back()->with('success_message',$event->cover_image?'Event header image saved successfully.':'Event header image removed.');}
 public function orders(Event $event){$event->loadCount('orders');$orders=$event->orders()->with('items')->latest()->paginate(30);echo $this->admin_after_login_layout('Event Registrations','events.orders',compact('event','orders'));}
 private function save(Request $r,Event $event){
  $r->merge(['slug'=>Str::slug($r->input('slug')?:$r->input('title'))]);
  $d=$r->validate(['title'=>'required|string|max:255','slug'=>['required','string','max:255',Rule::unique('events','slug')->ignore($event->id)],'summary'=>'nullable|string|max:1000','description'=>'nullable|string','venue_name'=>'nullable|string|max:255','venue_address'=>'nullable|string|max:1000','timezone'=>'required|string|max:50','starts_at'=>'required|date','ends_at'=>'required|date|after:starts_at','registration_opens_at'=>'nullable|date','registration_closes_at'=>'nullable|date|before_or_equal:starts_at','capacity'=>'nullable|integer|min:1','max_seats_per_order'=>'required|integer|min:1|max:100','currency'=>'required|string|size:3','status'=>['required',Rule::in(['draft','published','cancelled'])],'allow_guest_registration'=>'nullable|boolean','collect_attendee_details'=>'nullable|boolean','cover_image'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:5120','remove_cover_image'=>'nullable|boolean','tickets'=>'required|array|min:1','tickets.*.name'=>'required|string|max:100','tickets.*.price'=>'required|numeric|min:0','tickets.*.capacity'=>'nullable|integer|min:1','tickets.*.maximum_per_order'=>'required|integer|min:1|max:100','tickets.*.is_active'=>'nullable|boolean','addons'=>'nullable|array','addons.*.name'=>'nullable|string|max:120','addons.*.category'=>'nullable|string|max:30','addons.*.price'=>'nullable|numeric|min:0','addons.*.pricing_type'=>['nullable',Rule::in(['per_seat','per_order'])],'addons.*.is_active'=>'nullable|boolean','fields'=>'nullable|array','fields.*.label'=>'nullable|string|max:120','fields.*.field_type'=>['nullable',Rule::in(['text','email','phone','textarea','select','checkbox'])],'fields.*.options'=>'nullable|string|max:1000','fields.*.is_required'=>'nullable|boolean','fields.*.applies_to'=>['nullable',Rule::in(['order','attendee'])]]);
  $d['requires_login']=$r->boolean('requires_login');$d['allowed_user_types']=$d['requires_login']?array_values(array_intersect(array_map('intval',$r->input('allowed_user_types',[])),[2,3])):null;if($d['requires_login']&&!$d['allowed_user_types'])return back()->withInput()->withErrors(['allowed_user_types'=>'Select Business owners, Guests, or both.']);$d['allow_guest_registration']=!$d['requires_login'];
  $oldCover=$event->cover_image;if($r->hasFile('cover_image')){$dir=public_path('uploads/events');if(!is_dir($dir))mkdir($dir,0775,true);$name=Str::uuid().'.'.$r->file('cover_image')->extension();$r->file('cover_image')->move($dir,$name);$d['cover_image']='uploads/events/'.$name;}elseif($r->boolean('remove_cover_image')){$d['cover_image']=null;}else{unset($d['cover_image']);}unset($d['remove_cover_image']);
  DB::transaction(function()use($d,$event){$ed=collect($d)->except(['tickets','addons','fields'])->all();$ed['allow_guest_registration']=(bool)($d['allow_guest_registration']??false);$ed['collect_attendee_details']=(bool)($d['collect_attendee_details']??false);$ed[$event->exists?'updated_by':'created_by']=auth('admin')->id();$event->fill($ed)->save();$event->tickets()->delete();foreach($d['tickets'] as $i=>$row)$event->tickets()->create(array_merge($row,['is_active'=>(bool)($row['is_active']??false),'sort_order'=>$i]));$event->addons()->delete();foreach($d['addons']??[] as $i=>$row)if(!blank($row['name']??null))$event->addons()->create(array_merge($row,['is_active'=>(bool)($row['is_active']??false),'sort_order'=>$i]));$event->fields()->delete();$keys=[];foreach($d['fields']??[] as $i=>$row)if(!blank($row['label']??null)){$base=Str::slug($row['label'],'_')?:'question';$key=$base;$n=2;while(in_array($key,$keys,true))$key=$base.'_'.$n++;$keys[]=$key;$event->fields()->create(['field_key'=>$key,'label'=>$row['label'],'field_type'=>$row['field_type']??'text','options'=>array_values(array_filter(array_map('trim',explode(',',$row['options']??'')))),'is_required'=>(bool)($row['is_required']??false),'applies_to'=>$row['applies_to']??'order','sort_order'=>$i]);}});
  if($oldCover&&$oldCover!==$event->fresh()->cover_image&&is_file(public_path($oldCover)))@unlink(public_path($oldCover));
  return redirect()->route('admin.events.index')->with('success_message','Event saved successfully.');
 }
}
